# Generated by Django 4.2.1 on 2023-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customtokenblacklistoutstanding"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="access",
            field=models.CharField(default="uyitygik", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdevice",
            name="refresh",
            field=models.CharField(default="ifyuitd", max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CustomTokenBlacklistOutstanding",
        ),
    ]
