# Generated by Django 4.2.1 on 2023-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userdevice_access_userdevice_refresh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="access",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="refresh",
            field=models.CharField(max_length=300),
        ),
    ]
